<?php

namespace AppBundle\Repository;

/**
 * AdresseUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
