<?php

namespace AppBundle\Repository;

/**
 * CategServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findServicesByNomPrestataire($nom){
        $qb = $this->createQueryBuilder('cs')
            ->leftJoin('cs.prestataires', 'p')->addSelect('p');

        $qb->andWhere("p.nom like :nom");

        $qb->setParameter('nom',$nom);

        return $qb->getQuery()->getResult();
    }
}
