<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *  Retourne le nombre de Commentaires publiés
     */
    public function countCommentaires() {

        $qb = $this->createQueryBuilder('c')->select('COUNT(c)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
