<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\QueryBuilder;
/**
 * InternauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternauteRepository extends \Doctrine\ORM\EntityRepository {

    public function findInternaute($id) {

        $qb = $this->createQueryBuilder('i')->leftJoin('i.utilisateur','u')->addSelect('u');

        $qb->where('i.id=:id')->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
    public function getMyInternaute($id) {

        $qb = $this->createQueryBuilder('i')->leftJoin('i.utilisateur','u')->addSelect('u');

        $qb->where('i.utilisateur=:id')->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
