<?php

namespace AppBundle\Repository;

/**
 * MagicienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagicienRepository extends \Doctrine\ORM\EntityRepository
{
}
