<?php

namespace AppBundle\Repository;

/**
 * PasswordModificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordModificationRepository extends \Doctrine\ORM\EntityRepository
{
}
