<?php

namespace AppBundle\Repository;

/**
 * PrestataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestataireRepository extends \Doctrine\ORM\EntityRepository {

    public function findPrestataire($nom) {

        $qb = $this->createQueryBuilder('p')->leftJoin('p.utilisateur', 'u')->addSelect('u');

        $qb->where('p.nom=:nom')->setParameter('nom', $nom );

        return $qb->getQuery()->getResult();
    }

}
