<?php

namespace AppBundle\Repository;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findStagesByNomPrestataire($nom){
        $qb = $this->createQueryBuilder('st')
            ->leftJoin('st.prestataire', 'p')->addSelect('p');

        $qb->andWhere("p.nom like :nom");

        $qb->setParameter('nom',$nom);

        return $qb->getQuery()->getResult();
    }
}
