<?php

namespace AppBundle\Repository;

/**
 * WarriorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarriorRepository extends \Doctrine\ORM\EntityRepository
{
}
