app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
#login:
#    path: /login
#    defaults:
#        _controller: AppBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout