security:
    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm: bcrypt
          cost: 12
        AppBundle\Entity\Utilisateur:
          algorithm: bcrypt
          cost: 12

    role_hierarchy:
        ROLE_INTERNAUTE:    ROLE_USER
        ROLE_PRESTATAIRE:   ROLE_USER
        ROLE_ADMIN:         [ROLE_INTERNAUTE,ROLE_PRESTATAIRE,ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        main:
          entity:
            class:    AppBundle\Entity\Utilisateur
            property: username
          
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            provider:     main
            form_login:
                login_path: login
                check_path: login_check

            logout:
              path:       logout
              target:     /login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/internaute, roles: ROLE_INTERNAUTE }
        - { path: ^/prestataire, roles: ROLE_PRESTATAIRE }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }